version: '3'

services:
  bot:
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    pull_policy: build
    networks:
      - network
    environment:
      - TOKEN=${TOKEN}
      - USER_AGENT=${USER_AGENT}
      - API_URL=${API_URL}
      - DATABASE_URL=${DATABASE_URL}

  postgres:
    image: postgres:13.11
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    networks:
      - network
    volumes:
      - postgresdata:/var/lib/postgresql/data

networks:
  network:
    driver: bridge

volumes:
  postgresdata:
